theme: jekyll-theme-hacker
title: Hi. I am Gaurav Mittal
description: I build software products and my focus areas are the product functionality, software architecture and backend implementation. Below are a few that I’ve built from scratch in recent years.
